
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jul 10 14:51:11 CST 2011
//----------------------------------------------------

package querymanager.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AS = 42;
  public static final int FROM = 18;
  public static final int GT = 83;
  public static final int TIME = 63;
  public static final int GROUP = 25;
  public static final int OUTER = 51;
  public static final int NATURAL = 48;
  public static final int TRIGGER = 12;
  public static final int TABLE = 14;
  public static final int GE = 84;
  public static final int CROSS = 62;
  public static final int ASC = 67;
  public static final int LIKE = 20;
  public static final int SCHEMA = 50;
  public static final int COMMA = 69;
  public static final int SUM = 30;
  public static final int JOIN = 39;
  public static final int RPAREN = 73;
  public static final int INNER = 52;
  public static final int LT = 81;
  public static final int ALL = 44;
  public static final int DEVIDE = 78;
  public static final int DOUBLE = 88;
  public static final int LPAREN = 72;
  public static final int CONNECT = 65;
  public static final int CARCHAR = 57;
  public static final int FALSE = 61;
  public static final int NOT = 40;
  public static final int LE = 82;
  public static final int VIEW = 22;
  public static final int MIN = 34;
  public static final int EQ = 79;
  public static final int INTO = 17;
  public static final int EXCEPT = 46;
  public static final int SELECT = 8;
  public static final int NUMBER = 87;
  public static final int FULL = 49;
  public static final int TRUE = 60;
  public static final int ALTER = 4;
  public static final int PLUS = 75;
  public static final int INDEX = 10;
  public static final int EXISTS = 66;
  public static final int ORDER = 28;
  public static final int UNION = 47;
  public static final int DELETE = 7;
  public static final int CHAR = 54;
  public static final int STAR = 77;
  public static final int ESCAPE = 35;
  public static final int MAX = 33;
  public static final int DOT = 74;
  public static final int INT = 56;
  public static final int AVG = 31;
  public static final int REFERENCE = 38;
  public static final int NULL = 41;
  public static final int SEMICOLON = 71;
  public static final int EOF = 0;
  public static final int BETWEEN = 23;
  public static final int INTERSECT = 45;
  public static final int WHERE = 32;
  public static final int COUNT = 24;
  public static final int MINUS = 76;
  public static final int IS = 53;
  public static final int UNIQUE = 6;
  public static final int IN = 21;
  public static final int DATE = 55;
  public static final int OR = 86;
  public static final int SET = 29;
  public static final int error = 1;
  public static final int ON = 43;
  public static final int DESC = 68;
  public static final int ID = 90;
  public static final int DATABASE = 15;
  public static final int COLON = 70;
  public static final int CHECK = 11;
  public static final int BY = 27;
  public static final int ASSERT = 13;
  public static final int VALUES = 16;
  public static final int ANY = 64;
  public static final int CREATE = 2;
  public static final int UNKNOWN = 59;
  public static final int CASCADE = 58;
  public static final int UPDATE = 3;
  public static final int INSERT = 5;
  public static final int STRING = 89;
  public static final int NEQ = 80;
  public static final int PRIMARY = 36;
  public static final int AND = 85;
  public static final int DROP = 9;
  public static final int KEY = 37;
  public static final int HAVING = 26;
  public static final int DISTINCT = 19;
}

